#!/bin/sh
set -eu
exec 2>&1

BASE=/openbayes/home/coding-worker
set -a
. "$BASE/config/worker.env"
set +a

: "${LITELLM_BASE_URL:?LITELLM_BASE_URL is required}"
: "${LITELLM_API_KEY:?LITELLM_API_KEY is required}"

LITELLM_HOST=${LITELLM_BASE_URL#*://}
LITELLM_HOST=${LITELLM_HOST%%/*}
LITELLM_HOST=${LITELLM_HOST%%:*}
export ANTHROPIC_BASE_URL=$LITELLM_BASE_URL
export ANTHROPIC_API_KEY=$LITELLM_API_KEY
export ANTHROPIC_AUTH_TOKEN=$LITELLM_API_KEY
export NO_PROXY="localhost,127.0.0.1,${LITELLM_HOST}${NO_PROXY:+,$NO_PROXY}"
export no_proxy=$NO_PROXY

export HOME=/openbayes/home/coding-worker-home
export USER=codingworker
export LOGNAME=codingworker
export PATH=/openbayes/home/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

exec chpst -u codingworker:codingworker "$BASE/.venv/bin/python" "$BASE/worker/watcher.py"
